[theme]
base = "light"
primaryColor = "#cc1f1f"
backgroundColor = "#f1f1f1"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"
font = "sans serif"
baseRadius = "none"

[server]
enableStaticServing = false

[browser]
gatherUsageStats = false
